Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QueueUnderflow.Data;
using QueueUnderflow.Models;
using System.Text.RegularExpressions;
using System;
using System.Collections.Generic;

namespace QueueUnderflow.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CategoriesController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager
            )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        public IActionResult Index()
        {
            if (TempData["notification"] != null)
            {
                ViewBag.Notification = TempData["notification"];
                ViewBag.Icon = TempData["icon"];
                ViewBag.Type = TempData["type"];
            }

            var categories = db.Categories.Include("Discussions");
            ViewBag.Categories = categories;

            return View();
        }

        public ActionResult Show(int id)
        {
            Category categ = db.Categories.Include("Discussions").Where(cat => cat.Id == id).First();

            int _perPage = 3;

            IOrderedQueryable<Discussion>? discussions;
            var sortType = Convert.ToString(HttpContext.Request.Query["sort"]);
            ViewBag.SortType = sortType;
            if (sortType == "answers")
            {
                discussions = db.Discussions.Include("Category").Include("User")
                .Where(disc => disc.CategoryId == id).OrderByDescending(a => a.Answers.Count() );
            }
            else
            {
                discussions = db.Discussions.Include("Category").Include("User")
                .Where(disc => disc.CategoryId == id).OrderByDescending(a => a.Date);
            }

            int totalItems = discussions.Count();

            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);
            
            var offset = 0;
            
            if (!currentPage.Equals(0))
            {
                offset = (currentPage - 1) * _perPage;
            }
            var paginatedDiscussions = discussions.Skip(offset).Take(_perPage);

            ViewBag.lastPage = Math.Ceiling((float)totalItems / (float)_perPage);
            ViewBag.Discussions = paginatedDiscussions;
            return View(categ);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult New(Category categ)
        {
            if (User.IsInRole("Admin"))
            {
                if (ModelState.IsValid)
                {
                    db.Categories.Add(categ);
                    db.SaveChanges();
                    TempData["notification"] = "Category added";
                    TempData["icon"] = "bi-plus-circle";
                    TempData["type"] = "bg-success";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            else
            {
                TempData["notification"] = "Not allowed";
                TempData["icon"] = "bi-exclamation-triangle";
                TempData["type"] = "bg-danger";
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Category categ = db.Categories.Find(id);

            return View( categ );
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(int id, Category requestCateg)
        {
            Category categ = db.Categories.Find(id);

            if (User.IsInRole("Admin"))
            {
                if (ModelState.IsValid)
                {
                    categ.CategoryName = requestCateg.CategoryName;
                    db.SaveChanges();
                    TempData["notification"] = "Category edited.";
                    TempData["icon"] = "bi-pencil";
                    TempData["type"] = "bg-info";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(requestCateg);
                }
            }
            else
            {
                TempData["notification"] = "Not allowed";
                TempData["icon"] = "bi-exclamation-triangle";
                TempData["type"] = "bg-danger";
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (User.IsInRole("Admin"))
            {
                var categ = db.Categories
                .Include("Discussions")
                .Include("Discussions.Answers")
                .Where(c => c.Id == id)
                .First();

                if (categ.Discussions.Count > 0)
                {
                    foreach (var discussion in categ.Discussions)
                    {
                        if (discussion.Answers.Count() > 0)
                        {
                            foreach (var ans in discussion.Answers)
                            {
                                db.Answers.Remove(ans);
                            }
                        }
                        db.Discussions.Remove(discussion);
                    }
                }

                db.Categories.Remove(categ);
                db.SaveChanges();

                TempData["notification"] = "Category deleted.";
                TempData["icon"] = "bi-trash3";
                TempData["type"] = "bg-danger";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["notification"] = "Not allowed";
                TempData["icon"] = "bi-exclamation-triangle";
                TempData["type"] = "bg-danger";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/DiscussionInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model QueueUnderflow.Models.Discussion
@{
    string timeAgo = @Model.Date.ToString("MMMM dd, yyyy");
}


<div class="card-body article-card">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <div class="card-text">@Html.Raw(Model.Content)</div>
        <div class="text-end">
            <small>started @timeAgo</small>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card" style="border:none !important;">

                <form method="post" action="/Discussions/Show/@Model.Id">
                    <div class="card-body">
                        <input type="hidden" name="DiscussionId" value="@Model.Id" />
                        <br />

                        @Html.TextArea("Content", "", new { @class = "form-control summernote"})
                        @Html.ValidationMessage("Content", null, new { @class = "text-danger" })
                        <button class="btn btn-success mt-2" type="submit">Answer</button>
                    </div>
                </form>

            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<div class="px-4">
    @foreach (QueueUnderflow.Models.Answer ans in Model.Answers)
    {
        <div class="d-flex flex-start mb-4">
            <div class="card w-100">
                <div class="card-body p-4">
                    <div class="">
                        <h5>@ans.User.UserName</h5>
                        <p class="small">@ans.Date.ToString("MMMM dd, yyyy")</p>
                        <div class="card-text">@Html.Raw(ans.Content)</div>
                    </div>
                    @if (User.IsInRole("Admin") || ans.User.Id == @ViewBag.CurrentUserId)
                    {
                        <div class="d-flex">
                            @if (ans.User.Id == ViewBag.CurrentUserId)
                            {
                                <a class="btn btn-outline-primary" href="/Answers/Edit/@ans.Id"><i class="bi bi-pencil-square"></i></a>
                            }
                            <div>
                                <form method="post" action="/Answers/Delete/@ans.Id">
                                    <button class="btn btn-outline-danger mx-2" type="submit"><i class="bi bi-trash"></i></button>
                                </form>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/DiscussionPreview.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model QueueUnderflow.Models.Discussion
@{
    string timeAgo;
    var timePassed = DateTime.Now - @Model.Date;
    var hoursPassed = (int) timePassed.TotalHours;
    var daysPassed = (int) timePassed.TotalDays;
    var minutesPassed = (int) timePassed.TotalMinutes;
    if (60 > minutesPassed)
    {
        if (1 > minutesPassed)
        {
            timeAgo = "less than a minute ago";
        } else if (minutesPassed == 1)
        {
            timeAgo = "one minute ago";
        } else
        {
            timeAgo = minutesPassed + " minutes ago";
        }
    } 
    else if (24 > hoursPassed)
    {
        if (hoursPassed == 1)
        {
            timeAgo = "one hour ago";
        }
        else
        {
            timeAgo = hoursPassed + " hours ago";
        }
    }
    else if (30 > daysPassed)
    {
        if (daysPassed == 1)
        {
            timeAgo = "yesterday";
        }
        else
        {
            timeAgo = daysPassed + " days ago";
        }
    }
    else if (365 > daysPassed)
    {
        timeAgo = "on " + @Model.Date.ToString("MMMM dd");
    }
    else
    {
        timeAgo = @Model.Date.ToString("MMMM dd, yyyy");
    }

}


<a href="/Discussions/Show/@Model.Id" class="link-dark more"> <h5 class="card-title">@Model.Title</h5> </a>
<div class="card-text">@Html.Raw(Model.Content)</div>
<div class="text-end">
    <small>started @timeAgo</small>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QueueUnderflow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.1/font/bootstrap-icons.css">

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QueueUnderflow.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">QueueUnderflow</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="New">Create category</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin") || User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Discussions" asp-action="New">New discussion</a>
                            </li>
                        }

                        <form class="d-flex mx-2" action="/Discussions/Index" method="post">
                            <input class="form-control me-2" type="text" name="searchValue" placeholder="Search" aria-label="Search">
                            <button class="btn btn-success" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - QueueUnderflow - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Summernote.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>